spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        show_sql: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jwt:
    secret: ${JWT_SECRET}

  security:
    kakao:
      auth:
        client: ${REST_API_KEY}
        redirect: ${REDIRECT_URI}